### ISSUE TITLE
Video player high quality support

### ISSUE THREAD

**Issue by mauriceoegerli** [ViewTube/viewtube-vue#105]
This issue depends on #79.
### description
Enable playback of higher video quality. At the moment, the maximum is 720p.
The problem is, Youtube returns higher quality streams with split audio and video.

There are several possible ways of achieving this:
- Sync playback on client side (Not practical, since two sources have to be streamed at once, which causes high network usage and the playback isn't very smooth. Browsers don't seem to like multiple media streams at once.)
- Reencode the two streams on the server and return a combined stream (Extremely resource intensive. Also, fluent-ffmpeg doesn't support two input streams.)
- Proxy the MPEG-DASH stream from Youtube, and do the playback on the client with the dash.js library (This is the way invidious does it)

### acceptance criterias
- [ ] Find a viable method of high quality streaming
- [ ] Implement server side
- [ ] Implement client side
- [ ] Add selectable quality entries to video player settings

**Comment by moisout** [comment]
Implemented in #912
