### ISSUE TITLE
Allow for managing all subscribed channel

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [ViewTube/viewtube-vue#124]
### description
As seen on this extremely long picture. Viewtube only show an handful of subscribed channels, while invidious instances allow to show all of the subscribed channels at once.
![ViewtubeVInvidious](https://user-images.githubusercontent.com/13170204/94411840-5265b580-0179-11eb-92d6-545dc01f0490.jpg)
### acceptance criterias
- [ ] Either show all subscribed channels at once
- [x] Opt. Or, display them, in a page like form, for a better performance on larger subscriptions lists.

**Comment by mauriceoegerli** [comment]
Hi, thanks for submitting this issue!
I think we're going to add pages to the subscription feed and the manage page, so i'll reference it here #123.

**Comment by mauriceoegerli** [comment]
This feature has been merged into dev (https://dev.viewtube.io), and will be released with v0.4.
