### ISSUE TITLE
SubIssue: Migrate Store to TypeScript

### ISSUE THREAD

**Issue by cyacedev** [ViewTube/viewtube-vue#129]
### description
Nuxt Store fully migrated to TypeScript

### acceptance criterias
- [x] Store is fully migrated
- [x] No issues from deepscan

**Comment by mauriceoegerli** [comment]
Closed by https://github.com/ViewTube/viewtube-vue/commit/01f507030b0df061425634eb1355d35b76349f58#commitcomment-43103509
