### ISSUE TITLE
Begin using a dedicated changelog

### ISSUE THREAD

**Issue by cyacedev** [ViewTube/viewtube-vue#136]
### description
Due to the development now being released as versions, it would make sense to use a changelog with a specific format.

### acceptance criterias
- [x] Changelog for next Release added
- [x] Opt. previous releases also appended

### resources
[keepachangelog.com](https://keepachangelog.com/en/1.0.0/) has some very useful information on how to format a changelog

**Comment by mauriceoegerli** [comment]
Existing changelog migrated: #158
