### ISSUE TITLE
No videos or searches are showing

### ISSUE THREAD

**Issue by Mennaruuk** [ViewTube/viewtube-vue#294]
**Describe the bug**
Neither videos nor searches show up.

**To Reproduce**

1. Go to [viewtube.io](https://viewtube.io)
2. Check for any videos showing up under Popular videos
3. Search for PewDiePie
4. Check if any videos show up as results for the search

**Expected behavior**
Trending videos should appear under Popular videos. Also, searching should work, and results should appear in response to searching.

**Screenshots**
![image](https://user-images.githubusercontent.com/52135169/105650893-3d790480-5e83-11eb-9e80-d8c88134a4f7.png)

![image](https://user-images.githubusercontent.com/52135169/105650902-48339980-5e83-11eb-9b06-184042c9929b.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 84.0.2

**Additional context**
Don't know if design is material, but whatever it is, it looks really elegant!

**Comment by mauriceoegerli** [comment]
Hi! Thank you for reporting this issue. The new release is coming very soon, which is supposed to fix this and issue #301. 
You can try out the dev version under https://dev.viewtube.io.

**Comment by Mennaruuk** [comment]
I share your feelings about the appearance. I think Invidious looks too simple, and your take on this with ViewTube is awesome. I love the look of VT!

A couple of things I noticed on the dev page:

- This is how the Settings page currently looks like on my smartphone:
![F74D432F-CB48-4B2A-945D-A11F8096ED36](https://user-images.githubusercontent.com/52135169/105824248-18bc8400-5f8c-11eb-8997-eb9faa37f1ad.jpeg)
Also the About page:
![85998AB3-8845-4345-9022-DFC0D5CE42E7](https://user-images.githubusercontent.com/52135169/105824841-e2cbcf80-5f8c-11eb-966c-4da181e56318.jpeg)

- The text to the right of the checkboxes for instance selection creates excessive space where I have to swipe right to see everything. Also, there is no button to return to homepage after choosing an instance (beside refreshing). Clicking the browser’s back button returned me to the site I was on before ViewTube:
![9871DFFD-FA18-44B4-92FF-9A0425ADF5B5](https://user-images.githubusercontent.com/52135169/105824453-5d481f80-5f8c-11eb-9125-65544b3de39f.jpeg)

Thank you for this great site! 🙏

**Comment by mauriceoegerli** [comment]
Thank you for your feedback! What phone are you using?

**Comment by Mennaruuk** [comment]
iPhone X

**Comment by mauriceoegerli** [comment]
I have released v0.5 now, which should fix this issue and #301. I also have created new issues for the other things you mentioned here.

**Comment by Mennaruuk** [comment]
**_THANK YOU!!!!_**
