### ISSUE TITLE
Invidious Instances Not Being Fetched

### ISSUE THREAD

**Issue by Mennaruuk** [ViewTube/viewtube-vue#301]
**Describe the bug**
For some reason, ViewTube isn't fetching Invidious instances.

**To Reproduce**
1. Visit https://viewtube.io
2. Click on Profile icon
3. Click on **instances**
4. Check for any Invidious instances

**Expected behavior**
Invidious instances should appear.

**Screenshot**
![image](https://user-images.githubusercontent.com/52135169/105746481-78c01580-5f0d-11eb-9114-ff9b80a4838e.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 84.0.2

**Additional context**
This looks better than YouTube imho.

**Comment by Mennaruuk** [comment]
I want to mention that "[invidio.us is now deprecated, invidious.io is the new domain.](https://github.com/iv-org/invidious/issues/1694)"

"The invidious-redirect website ( invidio.us ) is now https://redirect.invidious.io/

The instance API ( instances.invidio.us ) is now https://api.invidious.io/

The uptimerobot page ( uptime.invidio.us ) is now https://uptime.invidious.io/"

**Comment by mauriceoegerli** [comment]
v0.5 is now released
