### ISSUE TITLE
Errors should be indicated in the interface with the option to retry

### ISSUE THREAD

**Issue by cloudrac3r** [ViewTube/viewtube-vue#316]
**Describe the bug**
Currently if a request fails then it doesn't inform the person what has happened in any way, leaving them to wonder if it is still loading.

**Expected behavior**
If a request fails then there should be a notice on screen saying so, including the error message provided by the server.
Ideally there would also be a button to retry the last request, which the person can use if they suspect that the error is temporary.

**Comment by mauriceoegerli** [comment]
Hi, thank you very much for creating this issue! I will look into improving the display of errors. The button to retry is a good suggestion.
