### ISSUE TITLE
Videos unplayable on iOS regardless of instance

### ISSUE THREAD

**Issue by Mennaruuk** [ViewTube/viewtube-vue#353]
**Describe the bug**
Videos are stuck loading in iOS. This happens regardless of what instance I choose. 

**To Reproduce**

1. Go to [viewtube.io](https://viewtube.io) on an iPhone running iOS 14
2. Choose a currently working instance
3. Try to play any video

**Expected behavior**
Videos should play on iOS. I tried seeing any console errors using Firefox's Responsive Design mode (where I can simulate an iPhone), but I couldn't reproduce it there.

**Screenshots**

https://user-images.githubusercontent.com/52135169/107126721-6a63e900-687f-11eb-83c9-d497a8e43141.mp4

**Smartphone (please complete the following information):**

- Device: iPhone X
- OS: 14.4
- Browser: Safari

**Additional context**
Thanks for maintaining ViewTube. I actually made all my YouTube videos redirect to ViewTube using Privacy Redirect, and I couldn't be happier.

**Comment by RouterCFW** [comment]
Same for me nothing plays on iOS

**Comment by moisout** [comment]
Can someone test if playback is working on ios on the dev instance? https://dev.viewtube.io @RouterCFW @Mennaruuk

**Comment by RouterCFW** [comment]
Just tested it works fine :)

**Comment by moisout** [comment]
viewtube v0.6.0 has been released👍
