### ISSUE TITLE
Thumbnails when seeking

### ISSUE THREAD

**Issue by Mennaruuk** [ViewTube/viewtube-vue#355]
### Description
YouTube and Invidious both show thumbnails as the user seeks through the video. It'd bring ViewTube one step forward to have thumbnails when sliding through the video's time!

https://user-images.githubusercontent.com/52135169/107134809-6eb1f580-68c3-11eb-9598-d0466f1ddbde.mp4

**Comment by Mennaruuk** [comment]
My bad, I must've been dreaming. This is already a feature!

![image](https://user-images.githubusercontent.com/52135169/107135496-3a413800-68c9-11eb-9de8-cc7c3d690fc3.png)

**Comment by mauriceoegerli** [comment]
It doesn't work sometimes, because the thumbnails are fetched from invidious, and it's not always reliable.
