### ISSUE TITLE
Selected invidious instance not used

### ISSUE THREAD

**Issue by ckVendrix** [ViewTube/viewtube-vue#62]
### description
If you select an instance through the instance selector window, your preference is saved. But when making a call to the api, this preference gets ignored

### acceptance criterias
- [x] Correctly call api client-side
- [ ] Find a way to communicate to server which api to use

**Comment by moisout** [comment]
Invidious isn't used for server-side api calls anymore.
The homepage is fetched daily, not invoked by a user.
Comments are only fetched client-side.
