### ISSUE TITLE
Captions support for videoplayer

### ISSUE THREAD

**Issue by mauriceoegerli** [ViewTube/viewtube-vue#80]
### description
Display captions in videoplayer

### acceptance criterias
- [ ] Add menu to select language, if available
- [ ] Display captions on top of video
- [ ] Sync captions with video playback progress

**Comment by reeseovine** [comment]
Apologies for necro-bumping but I don't see where to turn captions on. I've checked a few videos now, some that use YT's auto-captions and some that have dedicated ones, but they do not have any in ViewTube.
