### ISSUE TITLE
Viewtube doesn´t support ¨big¨ subscriptions lists.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [ViewTube/viewtube-vue#89]
**Describe the bug**
After trying to import a >800 channels list in my subscriptions, it doesn’t import them correctly, despite parsing them correctly after uploading the .json file.
**To Reproduce**

1. Go into your account settings.
2. Click on 'Import subscriptions'
3. Append your large invidious OPML subscription file.
	a. Notice that all the channels are correctly parsed and added.
4. The import notification announce us that our subscriptions have been imported. But none are present.

**Expected behavior**
I would have expected to see my channels subscriptions appear.

**Screenshots**
https://files.catbox.moe/izs92h.webm

**Desktop (please complete the following information):**

- OS: Solus (GNU/Linux operating system)
- Browser : Firefox stable.
- Version : 90

**Additional context**
If wished, I can provide the file for testing purposes. 
And yeah, while I can potentially scrap a bunch of channels in this list, I do watch the content of most of them.

**Comment by mauriceoegerli** [comment]
Hi, thank you for reporting this issue. 

Do the subscriptions stay empty, or do they appear if you wait for 5-10 minutes?
It might be an issue with refreshing the feed after an import.

And if you could provide the file for testing, that would be very helpful. You can also email it to us at viewtube@m-o.dev if you dont want to post a public link or something.

**Comment by PoorPocketsMcNewHold** [comment]
It still stays empty.

Here's my subscription file. I don’t mind sharing it publicly for testing purposes.

https://litter.catbox.moe/j1khkq

**Comment by mauriceoegerli** [comment]
From my testing, big files with lots of channels are not the issue.
Because the file was exported from invidious, viewtube recognises the channel name, but doesn't correctly parse the ID and just silently continues.
I have created a feature request for invidious imports: #94.

**Comment by PoorPocketsMcNewHold** [comment]
Tested it, on the main instance after the v0.3 was released. It worked perfectly! Thanks for your work!
